#!/usr/bin/env bash
BIN=$1
[[ -n $BIN ]] || BIN=xmonad

STORE_PATH=$(nix --refresh build github:cassandracomar/nix-config#xmonad-personal --no-link --json | jq -rM '.[] | .outputs.out')

rm -f $BIN
ln -s $STORE_PATH/bin/xmonad $BIN
