#!/usr/bin/env bash
foreground=$1
background=$2
font=$3
horiz=$4
vert=$5

conky -qc ~/.xmonad/.conky_dzen | dzen2 -x $horiz -w '867' -h '40' -ta 'r' -bg $background -fg $foreground -y $vert -fn "$font" -e 'button2=;' -dock
